[package]
name = "hd"
version = "0.1.0"
authors = ["Michael Ekstrand <md@ekstrandom.net>"]
edition = "2018"
description = "Human-readable Display library"
license = "MIT"

[dependencies]
num-traits = "0.2"

[dev-dependencies]
proptest = "1"
